feat: (2) main configuration, networking and security modules
EndavaCollab/bvdapprenticeship2024-infra pull request #2
Opened 2024-08-07 20:11 UTC by mirunaenc

Added main configuration and global variables:
  - main.tf: Integrate modules, configure resource group and provider.
  - variables.tf: Define global variables.

Added networking module:
  - main.tf: Configure Virtual Network and Subnet.
  - outputs.tf: Output VNet and Subnet IDs.
  - variables.tf: Define networking variables.

 Added security module:
  - main.tf: Define Network Security Group and rules.
  - outputs.tf: Output NSG ID.
  - variables.tf: Define security variables.

2024-08-07 21:04 UTC, vlsts requested changes
Pe langa cele mentionate:
- Nu vad nicaieri un IP public, e nevoie de o resursa tip [`azurerm_public_ip`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip). ID-ul acestei resurse poate fi mai apoi mentionat intr-un block tip [`ip_configuration`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface#ip_configuration) in NIC.
- PR-ul nu pare facut (structural vorbind) asa cum trebuie, nu afecteaza cu ceva rezultatul final dar cred ca trebuia derivat tot din main, nu din PR-ul meu + atunci cand cele 2 PR-uri vor fi merged se vor rezolva conflictele (daca acestea apar, nu cred ca e cazul aici).

2024-08-07 21:04 UTC, vlsts commented on modules/variables.tf
Nu stiu daca are sens fisierul asta. Modulele sunt facute, nu cred ca mai trebuie sa facem inca un nivel de modul general care le include pe toate. Toate variabilele astea ar trebui inlocuite cu valori efective in main.

2024-08-07 21:04 UTC, vlsts commented on modules/main.tf
> +}
Nu e nevoie de block-ul de provider aici avand in vedere ca vom avea fisier `providers.tf` separat.

2024-08-07 21:04 UTC, vlsts commented on modules/main.tf
> +module "vm_rcb" {
Aici ar fi mai potrivit `rcb_vm` in loc de `vm_rcb` conform [naming convention](https://trello.com/c/TUSsBuxb/1-1devops-define-naming-convention).

2024-08-07 21:04 UTC, vlsts commented on modules/main.tf
> +module "vm_exm" {
Aici ar fi mai potrivit `exm_vm` in loc de `vm_exm` conform [naming convention](https://trello.com/c/TUSsBuxb/1-1devops-define-naming-convention).

2024-08-07 21:04 UTC, vlsts commented on modules/main.tf
> +}
Output-urile ar trebui puse in fisierul lor separat `outputs.tf`.

2024-08-07 21:04 UTC, vlsts commented on modules/main.tf
Fisierul ar trebui pus in afara folderului de module, mai ales ca in acest moment path-urile pentru importat module nu o sa mearga.

2024-08-08 07:54 UTC, en-nader-said requested changes

2024-08-08 07:54 UTC, en-nader-said commented on modules/security/main.tf
> +  }
Probabil e ok sa fie 80 aici, dar sa intrebam developerii ce porturi trebuie deschise pentru backend, pentru exm si rcb, iar pentru frontend cred ca putem configura noi sa fie ori 80 ori 8080.

2024-08-08 07:54 UTC, en-nader-said commented on providers.tf
> +}
Cred ca acest continut o sa-l punem in main.tf din root folder, iar acolo o sa trebuiasca sa configuram si backend, ca sa se salveze tfstate-ul in azure.

2024-08-08 08:02 UTC, en-nader-said commented on providers.tf
> +}
On second thought, putem sa facem asta cand ajungem la pipeline-ul de apply, realizez ca nu am scris in ticket despre asta

2024-08-08 08:30 UTC, en-vasiliuralucaelena requested changes

2024-08-08 08:30 UTC, en-vasiliuralucaelena commented on modules/networking/main.tf
> +  address_prefixes     = var.subnet_prefix
O sa avem nevoie de doua subnet-uri

2024-08-08 08:30 UTC, en-vasiliuralucaelena commented on modules/variables.tf
@vlsts o sa fie nevoie si de acest fisier de variabile insa ar trebui sa fie la acelasi nivel cu provider.tf, o sa il folosim sa definim variabilele pe care le vom adauga din exteriorul pipeline-ului

2024-08-08 14:53 UTC, en-vasiliuralucaelena commented
@mirunaenc  O sa inchid acest pull request din moment ce am creat unul nou cu un branch nou. Te las pe tine sa stergi branch-ul din acest PR cand esti sigura ca nu iti mai trebuie.

2024-08-08 14:53 UTC, closed without merging

2024-08-08 14:58 UTC, en-vasiliuralucaelena commented on modules/outputs.tf
> +  value       = module.rcb_vm.name
Treaba asta nu merge in terraform, daca ai nevoie sa folosesti in main.tf un output o sa scrii ceva de genul
`name =  module.rcb_vm.name`
Nu e nevoie sa le definesti iar, cred ca poti sa stergi tot fisierul asta