networking&security modules
EndavaCollab/bvdapprenticeship2024-infra pull request #3
Opened 2024-08-08 12:31 UTC by mirunaenc

Added networking and security modules & main configuration.

2024-08-08 12:42 UTC, en-nader-said requested changes

2024-08-08 12:42 UTC, en-nader-said commented on modules/main.tf
> +}
Asta de fapt o sa putem sa il redenumim in "azurerm_resource_group" "rg" sau ceva mai clar, main nu prea are sens aici, si o sa folosim un resource group care exista deja in azure, cel la care aveti acces. Si atunci o sa fie 'data' block in loc de 'resource'. Poti cauta in documentatie cum se pot folosi resurse care exista deja.

2024-08-08 12:42 UTC, en-nader-said commented on modules/main.tf
> +}
A si sa mutam main.tf de aici in root, adica inainte de folderul modules, iar toate sa le punem sub folderul terraform daca nu exista deja, ca sa fie toate intr-un loc.

2024-08-08 12:42 UTC, en-nader-said commented on modules/security/main.tf
> +    destination_address_prefix = "*"
Astea se pot combina intr-un singur rule, este practic acelasi port

2024-08-08 12:42 UTC, en-nader-said commented on modules/networking/main.tf
> +}
Aici ca sa separam proiectele macar putin, am putea sa facem 2 subnet-uri, deci vom avea nevoie si de 2 prefixes diferite

2024-08-08 13:11 UTC, vlsts commented on modules/outputs.tf
Cum a zis si @en-nader-said pentru main, aici ar trebui sa fie mutat fisierul un nivel mai sus.

2024-08-08 13:24 UTC, en-nader-said commented on modules/networking/main.tf
> +}
Nu am vazut ca e facut for_each la subnets, nevermind

2024-08-08 15:04 UTC, en-vasiliuralucaelena requested changes

2024-08-08 15:04 UTC, en-vasiliuralucaelena commented on modules/outputs.tf
> +  value       = module.rcb_vm.name
Treaba asta nu o sa mearga in terraform, daca ai nevoie sa folosesti un output in main.tf o sa scrii ceva de genul
`name = module.rcb_vm.name`
Nu e nevoie sa le definesi iar in root, cred ca poti sa stergi tot fisierul asta

2024-08-08 15:04 UTC, en-vasiliuralucaelena commented on modules/variables.tf
> +variable "resource_group_name" {
cred ca si fisierul asta trebuie mutat o data cu fisierul de modules/main.tf

2024-08-09 12:53 UTC, en-nader-said requested changes

2024-08-09 12:53 UTC, en-nader-said commented on terraform/modules/security/main.tf
> +    destination_port_range     = "80,8080"
Nu e corect aici, practic o sa deschide toate porturile dintre 80 pana la 8080 :)
O sa facem doar 2 rule-uri pentru 80 si 8080 separat

2024-08-09 12:53 UTC, en-nader-said commented on terraform/main.tf
> +    }
Aici vrem 2 subnet-uri, fiecare vm sa fie in subnet diferit ca sa fie relativ separat. Probabil trebuie de modificat si networking module si vm module ca sa poata functiona asa

2024-08-09 13:14 UTC, en-vasiliuralucaelena commented on terraform/main.tf
> +      name   = var.subnet_name
Nu am apucat sa discutam despre asta dar aici am avea doua optiune pe care sa le folosim cand dam valori la variabile:
1. Punem toate valorile aici in main.tf (ex: name = "exm-subnet-1")
2. Lasam cum e acum si creem un fisier .tfvars unde dam valori la variabile (despre asta va trebui sa va uitati putin cum se face)
Prima varianta e mai usoara dar cu a doua varianta mai invatati ceva
@en-nader-said

2024-08-09 13:14 UTC, en-vasiliuralucaelena commented on terraform/variables.tf
> +  description = "Name of the Resource Group for the projects"
Doar ca FYI, daca alegem sa punem valorile direct in main aici o sa ramana doar variabilele a caror valoare va veni din afara teraform-ului, cum ar fi secretele

2024-08-09 14:52 UTC, en-vasiliuralucaelena requested changes

2024-08-09 14:52 UTC, en-vasiliuralucaelena commented on terraform/main.tf
> +  nsg_name            = var.nsg_name
Daca ai ales sa pui valori in main.tf atunci trebuie facut pentru toate modulele la fel

2024-08-12 08:02 UTC, en-nader-said approved these changes

2024-08-12 08:23 UTC, en-vasiliuralucaelena approved these changes

2024-08-12 11:24 UTC, merged